dependency: 
	cp ../assignment9/poincare_section.m ../assignment9/RTBPfield.m ../assignment9/LCRTBP.m ../assignment9/select_eigenvector.m .
	
clean:
	rm -f poincare_section.m RTBPfield.m LCRTBP.m select_eigenvector.m results.txt
